export const GET_TOKEN = "GET_TOKEN";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const MINUS_PRODUCT_FROM_CART = "MINUS_PRODUCT_FROM_CART";
export const PLUS_PRODUCT_TO_CART = "PLUS_PRODUCT_TO_CART";
